name: deploy Websocket-Polygon container
on:
  # Can be manually triggered
  workflow_dispatch: {}
  # Trigger a deploy every time there is a merge to main
  push:
    branches:
    - main

env:
  # Set this to your AWS region, e.g. us-east-1
  AWS_REGION: us-east-1
  # Set this to the URI of your ECR repo
  ECR_REPO_URI: 340752807055.dkr.ecr.us-east-1.amazonaws.com/polygon-websocket-producer
  # Set this to the AWS role Github Actions will assume
  AWS_ROLE_TO_ASSUME: arn:aws:iam::340752807055:role/Github_Push_Images_to_ECR

jobs:
  deploy_to_ecr:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code repository in agent
        uses: actions/checkout@v4
        with:
          set-safe-directory: true

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        working-directory: ./Integration-elt/polygon-websocket
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          echo "Target repo: ${ECR_REPO_URI}:${IMAGE_TAG}"
          docker build --platform linux/amd64 -t ${ECR_REPO_URI}:${IMAGE_TAG} .
          docker tag ${ECR_REPO_URI}:${IMAGE_TAG} ${ECR_REPO_URI}:latest

          # Push both tags
          docker push ${ECR_REPO_URI}:${IMAGE_TAG}
          docker push ${ECR_REPO_URI}:latest
          
          # Set output for use in subsequent steps
          echo "image=${ECR_REPO_URI}:${IMAGE_TAG}" >> $GITHUB_OUTPUT
